syms x y z vx vy vz T Tx R Om an ae ad
Ty = 180*1e7*sec(x*1e-7)/(pi*R);
f = [ x + vx*Tx*T,...
      y + vy*Ty*T,...
      z - vz*T,...
      vx + (an-2*Om*vy*sin(x)+(vx*vz-vy^2*tan(x))/(R+z))*T,...
      vy + (ae+2*Om*(vx*sin(x)+vz*cos(x))+vy*(vz-vx*tan(x))/(R+z))*T,...
      vz + (ad+-2*Om*vy*cos(x)-(vy^2+vx^2)/(R+z))*T];
pretty(jacobian(f, [x, y, z, vx, vy, vz]))

f = [ x + vx*Tx*T,...
      y + vy*Ty*T,...
      z - vz*T,...
      vx + an*T,...
      vy + ae*T,...
      vz + ad*T];
pretty(jacobian(f, [x, y, z, vx, vy, vz]))